// Generated by CoffeeScript 1.6.3
(function() {
  var RubyMonsterGame;

  RubyMonsterGame = function() {
    window.Q = Quintus({
      development: true
    }).include("Sprites, Scenes, 2D, Input, UI, Touch, Anim").setup({
      maximize: true
    }).controls();
    Q.Sprite.extend("Player", {
      init: function(p) {
        this._super(p, {
          sprite: "ruby_monster",
          sheet: "sprite_map",
          animation: "basic",
          x: 105,
          y: 10,
          gravity: 0,
          vy: -1000,
          speed: 400
        });
        return this.add('2d, platformerControls, animation, alwaysFaceFront');
      }
    });
    Q.scene("level1", function(stage) {
      var player;
      stage.insert(new Q.Repeater({
        asset: "game_background.jpg",
        speedX: 0.5,
        speedY: 0.5,
        type: 0
      }));
      player = new Q.Player();
      stage.insert(player);
      return stage.add('viewport').follow(player, {
        x: true,
        y: true
      });
    });
    Q.animations("ruby_monster", {
      basic: {
        frames: [0, 1, 2],
        rate: 1 / 2
      }
    });
    return Q.load("game_background.jpg, sprite_map.png", function() {
      Q.sheet("sprite_map", "sprite_map.png", {
        tilew: 100,
        tileh: 100
      });
      return Q.stageScene("level1");
    });
  };

  window.addEventListener("load", RubyMonsterGame);

}).call(this);
