// Generated by CoffeeScript 1.6.3
(function() {
  var Components;

  Components = function() {
    return Q.component('alwaysFaceFront', {
      added: function() {
        return this.entity.on("step", this, "flipStep");
      },
      flipStep: function() {
        var factor, p;
        p = this.entity.p;
        factor = this.entity.p.backwards ? -1 : 1;
        if (p.vx * factor > 0 && p.flip !== 'x') {
          p.flip = 'x';
          this.entity.trigger('flipped');
        }
        if (p.vx * factor < 0 && p.flip) {
          p.flip = false;
          return this.entity.trigger('flipped');
        }
      }
    });
  };

  window.addEventListener("load", Components);

}).call(this);
