// Generated by CoffeeScript 1.6.3
(function() {
  var Platformer, random_color;

  random_color = function() {
    return "#" + Math.floor(Math.random() * 16777215).toString(16);
  };

  Platformer = function() {
    window.Q = Quintus({
      development: true
    }).include("Sprites, Scenes, 2D, Input, UI, Touch, Anim").setup({
      maximize: true
    }).controls();
    Q.Sprite.extend("Player", {
      init: function(p) {
        this._super(p, {
          sprite: "player",
          sheet: "herman",
          x: 105,
          y: 10,
          animation: "run",
          flip: "x",
          speed: 400,
          jumpSpeed: -600
        });
        return this.add('2d, platformerControls, animation, alwaysFaceFront');
      },
      step: function() {
        if (this.p.vx === 0) {
          return this.play("withGun");
        } else {
          return this.play("run");
        }
      }
    });
    Q.Sprite.extend("Gun", {
      init: function(p) {
        return this._super(p, {
          asset: "gun.png",
          flip: 'x',
          type: 0,
          x: 65,
          y: 10
        });
      },
      flipped: function() {
        this.p.x *= -1;
        return this.p.flip = this.container.p.flip;
      }
    });
    Q.Sprite.extend("Block", {
      init: function(p) {
        return this._super(p, {
          color: random_color(),
          w: 70,
          h: 70
        });
      },
      draw: function(ctx) {
        ctx.fillStyle = this.p.color;
        return ctx.fillRect(-this.p.cx, -this.p.cy, this.p.w, this.p.h);
      }
    });
    Q.scene("stage1", function(stage) {
      var gun, player;
      player = new Q.Player({});
      gun = new Q.Gun({});
      stage.insert(player);
      stage.insert(gun, player);
      player.on('flipped', gun, 'flipped');
      stage.add('viewport').follow(player, {
        x: true,
        y: true
      });
      return stage.insert(new Q.Block({
        x: 105,
        y: 500,
        w: 1000
      }));
    });
    Q.animations("player", {
      run: {
        frames: [4, 5, 6, 7],
        rate: 1 / 4
      },
      stand: {
        frames: [0],
        rate: 1
      },
      withGun: {
        frames: [1],
        rate: 1
      }
    });
    return Q.load("herman.png, gun.png, bullet.png", function() {
      Q.sheet("herman", "herman.png", {
        tilew: 140,
        tileh: 140
      });
      return Q.stageScene("stage1");
    });
  };

  window.addEventListener("load", Platformer);

}).call(this);
