// Generated by CoffeeScript 1.6.3
(function() {
  var Platformer, random_color;

  random_color = function() {
    return "#" + Math.floor(Math.random() * 16777215).toString(16);
  };

  Platformer = function() {
    window.Q = Quintus({
      development: true
    }).include("Sprites, Scenes, 2D, Input, UI, Touch, Anim").setup({
      maximize: true
    }).controls();
    console.log("Platformer");
    Q.Sprite.extend("Player", {
      init: function(p) {
        console.log("init herman");
        this._super(p, {
          sprite: "player",
          sheet: "herman",
          x: 105,
          y: 105,
          animation: "run",
          flip: "x",
          speed: 400,
          jumpSpeed: -600
        });
        return this.add('2d, platformerControls, animation');
      },
      step: function() {
        if (this.p.vx === 0) {
          this.play("stand");
        } else {
          this.play("run");
        }
        if (this.p.vx > 0) {
          this.p.flip = 'x';
        }
        if (this.p.vx < 0) {
          return this.p.flip = false;
        }
      }
    });
    Q.Sprite.extend("Block", {
      init: function(p) {
        return this._super(p, {
          color: random_color(),
          w: 70,
          h: 70
        });
      },
      draw: function(ctx) {
        ctx.fillStyle = this.p.color;
        return ctx.fillRect(-this.p.cx, -this.p.cy, this.p.w, this.p.h);
      }
    });
    Q.scene("stage1", function(stage) {
      var num, player, _i, _results;
      console.log("stage1!");
      player = new Q.Player({
        stage: stage
      });
      stage.insert(player);
      stage.add('viewport').follow(player, {
        x: true,
        y: true
      });
      _results = [];
      for (num = _i = 1; _i <= 10; num = ++_i) {
        _results.push(stage.insert(new Q.Block({
          x: num * 70 + 35,
          y: 200
        })));
      }
      return _results;
    });
    Q.animations("player", {
      run: {
        frames: [1, 2],
        rate: 1 / 4
      },
      stand: {
        frames: [0, 0, 0, 4],
        rate: 1
      }
    });
    return Q.load("herman.png", function() {
      Q.sheet("herman", "herman.png", {
        tilew: 140,
        tileh: 140
      });
      return Q.stageScene("stage1");
    });
  };

  window.addEventListener("load", Platformer);

}).call(this);
